In [121]:
import numpy as np

#Declaring a 0-D Array
arr = np.array(42)
print(f"1.This is a 0 Dimentional array: {arr}")

#Uni Dimentional Array
arr = np.array([1,2,3,4,5], dtype=np.int8)
print(f"2.This is a Uni Dimentional array: {arr}")
print(f"3.This array has {arr.ndim} dimention")
print(f"4.This is a {arr.shape} Matrix")

#2-Dimentional Array
#arr = np.array([[1,2,3,4],[5,6,7,8]])
arr = np.array([np.arange(1,5,1),np.arange(1,5,1)])
print(f"5.This is a Two dimentional Array: {arr}")
print(f"6.This array has {arr.ndim} dimentions")
print(f"7.This is a {arr.shape} Matrix")


#3-Dimentional Array
#Declareing a 2x(2x3)
arr = np.array([
     [[1,2,3,4],[5,6,7,8]],
     [[9,10,11,12],[13,14,15,16]]    
])
print(f"8.This is a Three Dimentional Array: {arr}")
print(f"9.This Array has {arr.ndim} Dimentions")
print(f"10.This is a {arr.shape} Matrix")


1.This is a 0 Dimentional array: 42
2.This is a Uni Dimentional array: [1 2 3 4 5]
3.This array has 1 dimention
4.This is a (5,) Matrix
5.This is a Two dimentional Array: [[1 2 3 4]
 [1 2 3 4]]
6.This array has 2 dimentions
7.This is a (2, 4) Matrix
8.This is a Three Dimentional Array: [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
9.This Array has 3 Dimentions
10.This is a (2, 2, 4) Matrix


In [122]:
#Exercise, Use indexing to aceess the following numbers
print(f"Exercise 1:{arr[0,0,0]}") #1
print(f"Exercise 2:{arr[1,0,2]}") #11
print(f"Exercise 3:{arr[1,1,1]}") #14
print(f"Exercise 4:{arr[0,0,3]}") #4
print(f"Exercise 5:{arr[0,1,2]}") #7

Exercise 1:1
Exercise 2:11
Exercise 3:14
Exercise 4:4
Exercise 5:7


In [123]:
#Slicing arrays
arr = np.array((0,1,2,3,4,5,6,7,8,9,10),dtype='int8')
print(f"This array has been sliced{arr[2:6 ] }")   # 2,3,4,5
print(f"This array has been sliced{arr[7:10] }") # 7,8,9
print(f"This array has been sliced{arr[0:3 ] }")   # 0,1,2


This array has been sliced[2 3 4 5]
This array has been sliced[7 8 9]
This array has been sliced[0 1 2]


In [124]:
#Data Types
print(arr.dtype)
my_full_names = np.array(("Chishibe","Martin","Kabwe"))
print(my_full_names.dtype)
my_arr = np.array([1.1,2.2,3.3],dtype='int8')
print(f"{my_arr} This array's Data type has been converted from float to integer")

int8
<U8
[1 2 3] This array's Data type has been converted from float to integer


In [125]:
#Checking The Dimension,Shape & reshaping
first_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(first_arr.ndim)
print(first_arr.shape)
Second_arr = first_arr.reshape(4,3)
print(Second_arr.shape)
print(Second_arr)
third_arr = Second_arr.reshape(-1)
print(third_arr)

1
(12,)
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [126]:
#Looping through an Array
fouth_arr = np.array( [[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]],dtype='int8')
# print(fouth_arr)
for x in fouth_arr:
    print(f"Iterating through an array with a for loop {x}")
    print(f"Outputing the array {fouth_arr}")

Iterating through an array with a for loop [[1 2 3]
 [4 5 6]]
Outputing the array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Iterating through an array with a for loop [[ 7  8  9]
 [10 11 12]]
Outputing the array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [127]:
#Array contatination
My_firstArray = np.array((1,2,3))
My_secondArray = np.array((4,5,6))
Conflated_array = np.concatenate((My_firstArray,My_secondArray))
print(f"This array has been conflated {Conflated_array}")


This array has been conflated [1 2 3 4 5 6]


In [128]:
#Spliting Arrays
split_array = np.array_split(Conflated_array,2)
print(f"This array has been split into 2{split_array}")


This array has been split into 2[array([1, 2, 3]), array([4, 5, 6])]


In [129]:
#Searching for Arrays
s = np.where(arr == 4)
print(f"The search result was {s}")

The search result was (array([4]),)


In [130]:
#Sorting an Array
print(np.sort(Conflated_array))



[1 2 3 4 5 6]
